name: indica_keyboard
description: "High-performance multilingual keyboard for Flutter supporting English, Hindi, and Marathi with native optimization."
version: 1.2.1
homepage: https://github.com/noelpinto47/indica_keyboard
repository: https://github.com/noelpinto47/indica_keyboard
issue_tracker: https://github.com/noelpinto47/indica_keyboard/issues
documentation: https://github.com/noelpinto47/indica_keyboard#readme

topics:
  - keyboard
  - multilingual
  - hindi
  - marathi
  - devanagari

screenshots:
  - description: 'Indica Keyboard supports multilingual input with native optimization'
    path: assets/images/indica_keyboard_banner.png

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.noelpinto47.indica_keyboard
        pluginClass: IndicaKeyboardPlugin
      ios:
        pluginClass: IndicaKeyboardPlugin

  # Assets for the keyboard icons and images
  assets:
    - assets/icons/
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # Custom fonts for Devanagari script support (Hindi/Marathi)
  fonts:
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-VariableFont_wdth,wght.ttf
          weight: 400
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
